
version: '3'

services:

  docker-doctorappointment-mysql:
    container_name: doctorappointment-mysql
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=12345671
    networks:
      - doctorappointment_mysql_net
    ports:
      - 3306:3306
  #
  springboot-docker-compose-doctorappointment-container:
    image: springboot-docker-compose-doctorappointment-app:1
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - docker-doctorappointment-mysql
    links:
      - docker-doctorappointment-mysql:mysql
    networks:
      - doctorappointment_mysql_net

networks:
  doctorappointment_mysql_net:
    driver: bridge